repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml          # Проверка синтаксиса YAML
      - id: end-of-file-fixer   # Убедиться в наличии пустой строки в конце файла
        exclude: \.(log|bin|png|jpg|pdf|log.*)$
      - id: trailing-whitespace # Удалить пробелы в конце строк
        exclude: \.(log|bin|png|jpg|pdf|log.*)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports, --show-error-codes]  # --strict
        additional_dependencies: [pydantic]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-r", "src/"]

  # - repo: https://github.com/pycqa/isort
  #  rev: 6.0.1                  # Укажите актуальную версию
  #  hooks:
  #    - id: isort
  #      name: isort (python)
  #      args: [--profile=black,
  #             --line-length=79,
  #             --multi-line=3,     # Стиль переноса импортов
  #             --trailing-comma,   # Добавлять запятую после последнего импорта
  #             #--force-sort-within-sections=false,  # Сортировка внутри секций
  #             --skip=__init__.py  # Игнорировать файлы
  #      ]
